name: MG Maquetes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5383401061408222
title: Fabricamos todo tipo de maquetes.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131318'
    - '#8aa6a9'
    - '#6d5e42'
    - '#489440'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.07960207434371114
  rhythmicContrast: 0.3559382180683315
purpose: []
