name: MG Maquetes
favicon: null
layout_spectrum: 0.3533890403341502
typography_spectrum: 0.5383401061408222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.004047817783430219
  lightness: 0.03843461279757321
  saturation: 0.07960207434371114
  rhythmicContrast: 0.3559382180683315
purpose: []
